apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: linodemachineproviderconfigs.linodeproviderconfig.linode.com
spec:
  group: linodeproviderconfig.linode.com
  names:
    kind: LinodeMachineProviderConfig
    plural: linodemachineproviderconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        image:
          type: string
        kind:
          type: string
        metadata:
          type: object
        pubkey:
          type: string
        region:
          type: string
        roles:
          items:
            type: string
          type: array
        type:
          type: string
      required:
      - region
      - type
      - image
      - pubkey
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
