apiVersion: v1
kind: Namespace
metadata:
  name: cluster01
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  generateName: cluster01-
  namespace: cluster01
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.254.0.0/16"]
        pods: 
            cidrBlocks: ["10.1.0.0/16"]
        serviceDomain: "cluster.local"
    providerConfig:
      value:
        apiVersion: "linodeproviderconfig/v1alpha1"
        kind: "LinodeClusterProviderConfig"
        authorizedKeys:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCagK9ZjexjQrxmCvQpPm4Da7qM9tQ/ldqAHqbORTqkZbAMMm8ASkBYFP8de4+y+K/BxV2iNDo/A/0Jkaw7uJSrH645vWzCbeX2S+hQMaQp2C7HE4aua8pwjL5d1q/YnU/tiznq2Lf74BTp4/mrl4pcmOTZdlUOa/tTN0ZZlZas0+KW9dr9cn4X78HT6n7vN0TOuQQMWTsw1aFxgdNMUDf6as7Z+RzILdG5J7G7QjFBbRzcj/yaRZGpmpaPvP+KV9J+8KsnjvoMNJuvBYQapWqZqv1yUqN45J2UQ9vvJ7H/p2u8+lYvGZ0wVbRB7PTHnsR8bOSW1f0BPoMDWkW+9ZCN asauber@MacBook-Pro-4.local"
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  generateName: master-
  labels:
    set: master
  namespace: cluster01
spec:
  providerConfig:
    value:
      apiVersion: "linodeproviderconfig/v1alpha1"
      kind: "LinodeMachineProviderConfig"
      roles:
      - Master
      region: "us-east"
      type: "g6-standard-2"
      image: "linode/ubuntu18.04"
  versions:
    kubelet: 1.11.3
    controlPlane: 1.11.3
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  generateName: node-
  labels:
    set: node
  namespace: cluster01
spec:
  providerConfig:
    value:
      apiVersion: "linodeproviderconfig/v1alpha1"
      kind: "LinodeMachineProviderConfig"
      roles:
      - Node
      region: "us-east"
      type: "g6-standard-2"
      image: "linode/ubuntu18.04"
  versions:
    kubelet: 1.11.3
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-api-token
  namespace: cluster01
type: Opaque
data:
  token: N2RhNWVjYzI3OTRlOGUwNzA3NmY0ZjJhOWFjZTkxZjA0M2VmNWJjZTk4ZDEyOGNjYzEwY2ZkMDZkMGExOWNhMw==
